// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * Handwritten extension of the generated Project class.
 *
 * Adds uploadImage() — a REST-based operation that cannot be generated by the
 * domain-map pipeline because BatchCreateScreens is a private endpoint with no
 * corresponding MCP tool in tools-manifest.json.
 *
 * The generated Project class is re-exported from this module, so consumers
 * import a single Project class that includes both generated and handwritten
 * methods.
 */

import { Project as GeneratedProject } from '../generated/src/project.js';
import { Screen } from '../generated/src/screen.js';
import { StitchError } from './spec/errors.js';
import {
  UploadImageInputSchema,
  type UploadImageInput,
} from './spec/upload.js';
import { UploadImageHandler } from './upload-handler.js';

export class Project extends GeneratedProject {
  /**
   * Upload an image file to the project and create a new Screen from it.
   *
   * WHY THIS IS NOT GENERATED:
   *   BatchCreateScreens is a private REST endpoint — it has no MCP tool
   *   in tools-manifest.json. It also requires reading a file from disk and
   *   base64-encoding it, which the codegen arg-routing model cannot express.
   *
   * @param filePath - Absolute or relative path to the image (PNG, JPG, JPEG, WEBP).
   * @param opts - Optional screen title and createScreenInstances flag.
   * @returns An array of Screen objects created from the upload.
   * @throws {StitchError} on file not found, unsupported format, or upload failure.
   *
   * @example
   * const [screen] = await project.uploadImage('./mockup.png', { title: 'Home Screen' });
   * const html = await screen.getHtml();
   */
  async uploadImage(
    filePath: string,
    opts?: Partial<Omit<UploadImageInput, 'filePath'>>,
  ): Promise<Screen[]> {
    const input = UploadImageInputSchema.parse({ filePath, ...opts });
    const handler = new UploadImageHandler(this['client']);
    const result = await handler.execute(this.projectId, input);

    if (!result.success) {
      throw new StitchError({
        code: result.error.code === 'FILE_NOT_FOUND'
          ? 'NOT_FOUND'
          : result.error.code === 'AUTH_FAILED'
          ? 'AUTH_FAILED'
          : 'UNKNOWN_ERROR',
        message: result.error.message,
        recoverable: result.error.recoverable,
      });
    }

    return result.screens;
  }
}
